// <auto-generated />
using GameServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109083431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameModels.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ac = 15,
                            AttackModifier = 2,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 2,
                            HitPoints = 22,
                            Name = "Ноори"
                        },
                        new
                        {
                            Id = 2,
                            Ac = 15,
                            AttackModifier = -1,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 2,
                            HitPoints = 7,
                            Name = "Гоблин"
                        },
                        new
                        {
                            Id = 3,
                            Ac = 13,
                            AttackModifier = 0,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 2,
                            HitPoints = 13,
                            Name = "Скелет бладфина"
                        },
                        new
                        {
                            Id = 4,
                            Ac = 20,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = "2d7",
                            DamageModifier = 4,
                            HitPoints = 80,
                            Name = "Оттокент"
                        },
                        new
                        {
                            Id = 5,
                            Ac = 5,
                            AttackModifier = 15,
                            AttackPerRound = 1,
                            Damage = "2d5",
                            DamageModifier = 2,
                            HitPoints = 30,
                            Name = "Скорпион"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
